"""Создание модели комнат, миграция в БД

Revision ID: c6797478d91d
Revises: 87e2d965a4ec
Create Date: 2025-09-08 08:54:07.836425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6797478d91d"
down_revision: Union[str, Sequence[str], None] = "87e2d965a4ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("room_title", sa.String(), nullable=False),
        sa.Column("room_description", sa.String(), nullable=True),
        sa.Column("room_price", sa.Integer(), nullable=False),
        sa.Column("room_quantity", sa.Integer(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.hotel_id"],
        ),
        sa.PrimaryKeyConstraint("room_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
