"""Первый запуск alembic

Revision ID: 87e2d965a4ec
Revises: 
Create Date: 2025-09-05 15:18:40.334332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e2d965a4ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=False),
    sa.Column('hotel_location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotels')
    # ### end Alembic commands ###
